#!/usr/bin/env python

# I added this for simple testing in browser that don't allow file:// xhr

import SimpleHTTPServer
import SocketServer

PORT = 8000

Handler = SimpleHTTPServer.SimpleHTTPRequestHandler

httpd = SocketServer.TCPServer(("", PORT), Handler)

print "serving at localhost:" + str(PORT)
print "http://localhost:" + str(PORT) + "/html/test_MapWidget.html"
httpd.serve_forever()