#!/bin/bash
./libs/closure-library/closure/bin/build/depswriter.py --root_with_prefix="js ../../../../js/" --output_file=gen/deps.js

cp tests/jsTestDriver.conf.proto.yaml tests/jsTestDriver.conf
libs/closure-library/closure/bin/build/closurebuilder.py \
  --input=tests/reqs.js \
  --root="tests" \
  --root="libs/closure-library" \
  --root="./js" \
  --namespace="z" \
  | sed "s#^#  - \.\./#" \
  >> tests/jsTestDriver.conf
